source "http://rubygems.org"

group :test do
  gem "rake", ">= 12.3.3"
  gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.4.0'
  gem "puppet-lint"
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppet-syntax", ">= 1.1.0"
  gem "puppetlabs_spec_helper", ">= 0.4.1"
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "beaker"
  gem "beaker-rspec"
  gem "vagrant-wrapper"
  gem "puppet-blacksmith"
  gem "guard-rake", ">= 0.0.9"
end
