source "http://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", "~> 4.10.1"
  gem "puppet-lint"
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppet-syntax", ">= 1.1.0"
  gem "puppetlabs_spec_helper"
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "beaker"
  gem "beaker-rspec"
  gem "vagrant-wrapper"
  gem "puppet-blacksmith", ">= 2.0.2"
  gem "guard-rake"
end
