source "http://rubygems.org"


gem "rake", ">= 12.3.3"
gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.2.0'
gem "puppet-lint"
gem "rspec-puppet", '~> 1.0.0'
gem "puppetlabs_spec_helper", ">= 0.4.1"
gem "rspec-system-puppet"
gem "vagrant-wrapper"
gem "puppet-syntax", ">= 1.1.0"

group :development do
  gem "puppet-blacksmith"
end
